//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt_PWI.Resources {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Projekt_PWI.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Jestem responsywny, współpraca ze mną jest prosta i jasna, dążę do perfekcji więc w cenie są wszelakie poprawki, wszystko po to, aby uzyskać jak najlepszy efekt..
        /// </summary>
        public static string aboutMe_cooperation_description {
            get {
                return ResourceManager.GetString("aboutMe.cooperation.description", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Współpraca.
        /// </summary>
        public static string aboutMe_cooperation_title {
            get {
                return ResourceManager.GetString("aboutMe.cooperation.title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Grafika jest moją pasją od kilku lat, jako freelancer zacząłem zajmować się nią profesjonalnie 2 lata temu, mam za sobą wiele udanych realizacji i zadowolonych klientów..
        /// </summary>
        public static string aboutMe_experience_description {
            get {
                return ResourceManager.GetString("aboutMe.experience.description", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Doświadczenie.
        /// </summary>
        public static string aboutMe_experience_title {
            get {
                return ResourceManager.GetString("aboutMe.experience.title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Od początku tworzę na legalnej &quot;stajni&quot; Adobe, dzięki czemu moje projekty są kompatybilne z punktami druku, co zapewnia szybką i bezproblemową współpracę..
        /// </summary>
        public static string aboutMe_software_description {
            get {
                return ResourceManager.GetString("aboutMe.software.description", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Software.
        /// </summary>
        public static string aboutMe_software_title {
            get {
                return ResourceManager.GetString("aboutMe.software.title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nazywam się &lt;span&gt;Dominik Obłoza&lt;/span&gt;. Grafiką zajmuję się od kilku lat, sprawnie poruszam się na płaszczyźnie rastrowej jak i wektorowej. Zawsze daje z siebie 139.34%, a dzięki zawzięciu osiągam wysoko postawione sobie cele..
        /// </summary>
        public static string aboutMe_whoAmI_description {
            get {
                return ResourceManager.GetString("aboutMe.whoAmI.description", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Kim jestem?.
        /// </summary>
        public static string aboutMe_whoAmI_title {
            get {
                return ResourceManager.GetString("aboutMe.whoAmI.title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Jeśli jesteś zainteresowany ofertą, skontaktuj się ze mną poprzez maila:.
        /// </summary>
        public static string footer_contact {
            get {
                return ResourceManager.GetString("footer.contact", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu freelancer kreator inspirator.
        /// </summary>
        public static string header_subtitle {
            get {
                return ResourceManager.GetString("header.subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Od loga do wizytówki, jestem w stanie zbudować indentyfikację wizualną twojej firmy..
        /// </summary>
        public static string info_identification_description {
            get {
                return ResourceManager.GetString("info.identification.description", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Identyfikacja.
        /// </summary>
        public static string info_identification_title {
            get {
                return ResourceManager.GetString("info.identification.title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Bannery, reklamy, ulotki - wszystko czego potrzebujesz aby powiedzieć światu o swojej firmie..
        /// </summary>
        public static string info_print_description {
            get {
                return ResourceManager.GetString("info.print.description", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Projekty do druku.
        /// </summary>
        public static string info_print_title {
            get {
                return ResourceManager.GetString("info.print.title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Projekty stron internetowych oraz reklam. Identyfikacja graficzna social mediów, wszystko czego potrzebujesz aby zaprezentować swoją stronę www..
        /// </summary>
        public static string info_web_description {
            get {
                return ResourceManager.GetString("info.web.description", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Web Design.
        /// </summary>
        public static string info_web_title {
            get {
                return ResourceManager.GetString("info.web.title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu O MNIE.
        /// </summary>
        public static string nav_aboutMe {
            get {
                return ResourceManager.GetString("nav.aboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu KONTAKT.
        /// </summary>
        public static string nav_contact {
            get {
                return ResourceManager.GetString("nav.contact", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu HOME.
        /// </summary>
        public static string nav_home {
            get {
                return ResourceManager.GetString("nav.home", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu INFO.
        /// </summary>
        public static string nav_info {
            get {
                return ResourceManager.GetString("nav.info", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu PORTFOLIO.
        /// </summary>
        public static string nav_portfolio {
            get {
                return ResourceManager.GetString("nav.portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Odwiedź mój profil na Behance.
        /// </summary>
        public static string socials_titles_behance {
            get {
                return ResourceManager.GetString("socials.titles.behance", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Odwiedź mój profil na Facebooku.
        /// </summary>
        public static string socials_titles_fb {
            get {
                return ResourceManager.GetString("socials.titles.fb", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Odwiedź mój profil na Instagramie.
        /// </summary>
        public static string socials_titles_instagram {
            get {
                return ResourceManager.GetString("socials.titles.instagram", resourceCulture);
            }
        }
    }
}
